config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root to: 'devices#index'
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }

  get 'terms', to: 'static_pages#terms'
  get 'help', to: 'static_pages#help'

  resources :templates do
    member do
      get :get_template
    end
  end
  resources :devices do
    member do
      get :get_device
      get :get_messages
      post :connect
      post :disconnect
    end
  end
end

app/views/shared/application_partials/_footer.html.erb
<footer class="footer-section">
    <div class="container-fluid">
        <p>
            <span>© Copyright 2018 Sinapse Energía
            </span>
            | All Rights Reserved</p>
    </div>
</footer>

app/views/shared/application_partials/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
<title>Iot Device Simulator</title>
<link rel="shortcut icon" href="../assets/favicon.ico" />

<%= csrf_meta_tags %>
<%= action_cable_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<!--[if gt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/shared/application_partials/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to image_tag('inner-logo.svg', alt: 'logo'), root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">

          <% if current_user %>

            <ul class="nav navbar-nav navbar-left navbar-top-links">
                <li class=<%= controller_name.include?('devices') ? 'active' : '' %> >
                  <%= link_to root_path do %>
                    <i class="device-icon"></i>
                    Devices
                  <% end %>
                </li>

                <li class=<%= controller_name.include?('templates') ? 'active' : '' %>>
                  <%= link_to templates_path do %>
                    <i class="template-icon"></i>
                    Templates
                  <% end %>
                </li>

                <li class=<%= controller_name.include?('static') ? 'active' : '' %> >
                  <%= link_to help_path do %>
                    <i class="help-icon"></i>
                    Help
                  <% end %>
                </li>
            </ul>

            <% end %>

            <!-- /.navbar-top-links -->
        </div>

        <% if current_user %>
        <ul class="nav navbar-right navbar-top-links">
            <li class="userdp dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <span class="user-profile">
                      <%= image_tag(current_user.avatar.url(:thumb)) %>
                    </span>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li>

                        <%= link_to edit_user_registration_path do %>
                          <i class="fa fa-user fa-fw"></i>
                          User Profile</a>
                        <% end %>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-gear fa-fw"></i>
                            Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <%= link_to destroy_user_session_path, method: :delete do %>
                        <i class="fa fa-sign-out fa-fw"></i>
                        Logout
                    <% end %>
                </li>
            </ul>
        </li>
    </ul>
    <% end %>
</div>

</nav>
<!---HEADER END --->