config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root to: 'devices#index'
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }

  get 'terms', to: 'static_pages#terms'
  get 'help', to: 'static_pages#help'

  resources :templates do
    member do
      get :get_template
    end
  end
  resources :devices do
    member do
      get :get_device
      get :get_messages
      post :connect
      post :disconnect
    end
  end
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :user
  belongs_to :template

  has_one :mqtt_broker
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "120x120#" },
                    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
                    :url => "/system/:attachment/:id/:style/:filename",
                    :default_url => "/assets/missing_device.png"

  validates_attachment_content_type :image, content_type: ["image/png", "image/jpg", "image/jpeg"]

  def interfaces
    self.interfaces_peripherals.try(:split, "\r\n")
  end

  def topic
    api_json&.dig('baseTopic')&.split('.')&.push('DEBUG')&.join('/')
  end

  def client_id
    if (api_json && api_json.dig('baseTopic')).present?
      api_json&.dig('baseTopic')&.split('.')[0]
    else
      nil
    end
  end
end

app/controllers/devices_controller.rb
require 'mqtt'
class DevicesController < ApplicationController
  before_action :fetch_device, except: [:index, :create, :new]

  def index
    fetch_data
  end

  def new
    @device = Device.new
    @devices = Device.all
    @templates = Template.all.map{|t| [t.name, t.id] }
  end

  def create
    @device = Device.new(device_params)
    if @device.save
      @device.create_mqtt_broker
      redirect_to :devices
    else
      redirect_back
    end
  end

  def edit
    @devices = Device.all
    @templates = Template.pluck(:name, :id)
  end

  def update
    if params[:device][:api_json].present?
      # For device management when upload json
      file = params[:device][:api_json].read
      data = JSON.parse(file)
      @device.update(api_json: data, template_id: params[:device][:template_id])
    else
      # Normal device updation
      @device.update(device_params)
    end
    redirect_to root_path
  end

  # MQTT device connect operations
  def connect
    begin
      if @device.api_json.present?
        if @device.mqtt_broker.connected == true
          render :json => {
                   message: 'Device already connected.'
                 }
        elsif
        @client = connect_mqtt_client

          # mqtt client publish and subscribe message
          @message = "Test message published at #{Time.now.strftime('%d-%m-%Y %H:%M:%S')}"
          @topic = @device.topic
          @client.publish(@topic, @message, retain= true)
          @client.subscribe(@topic)

          @templates = Template.pluck(:name, :id)
          if @client.connected?
            update_mqtt_details
            @device.mqtt_broker.update(connected: true)
            @device_tabs = render_to_string partial: 'devices/device_tabs',
                                            formats: :html,
                                            :locals => {device: @device, templates: @templates, message: @message, topic: @topic}
            render :json => {
                     :attachmentPartial => @device_tabs,
                     message: 'Device connected successfully.'
                   }
          end
        end
      else
        render :json => {
                 message: 'You didn\'t uploaded api_json, please upload it first'
               }
      end

    rescue MQTT::ProtocolException => mqtt_error
      render :json => {message: mqtt_error.message}
    rescue Exception => e
      render :json => {message: e.message}
    end
  end

  # MQTT device disconnect operations
  def disconnect
    begin
      if @device.mqtt_broker.connected == false
        render :json => {
                   message: 'Device already disconnected.',
               }
      else
        # device = Devices::ConnectService.new(params.dig(:mqtt_broker)).connect
        client = connect_mqtt_client
        @templates = Template.pluck(:name, :id)
        if client.connected?
          client.disconnect()
          @device.mqtt_broker.update(connected: false)
          @device_tabs = render_to_string partial: 'devices/device_tabs',
                                          formats: :html,
                                          :locals => {
                                            device: @device,
                                            templates: @templates
                                          }

          # Stop Thread
          Devices::CommunicationService.new(params.dig(:id), client, @device.topic).shutdown

          render :json => {
              :attachmentPartial => @device_tabs,
              message: 'Device disconnected successfully.'
          }
        end
      end
    rescue MQTT::ProtocolException => mqtt_error
      render :json => {message: mqtt_error.message}
    rescue Exception => e
      render :json => {message: e.message}
    end
  end

  def get_device
    @templates = Template.pluck(:name, :id)
    @message = "Test message published at #{Time.now.strftime('%d-%m-%Y %H:%M:%S')}"
    @topic = @device.topic
    render partial: 'device_tabs', locals: {device: @device, templates: @templates, message: @message, topic: @topic}
  end


  private

  def device_params
    params.require(:device).permit(:name, :interfaces_peripherals, :template_id, :user_id, :image)
  end

  def fetch_device
    @device = Device.find_by(id: params[:id])
  end

  def fetch_data
    @devices = Device.all.map{|d| [d.name, d.id] }
    @device = Device.find_by(id: @devices.first.last) rescue nil
    @templates = Template.all.map{|t| [t.name, t.id] }
    @message = "Test message published at #{Time.now.strftime('%d-%m-%Y %H:%M:%S')}"
    if !@device.nil?
    	@topic = @device.topic
    else
        @topic = "DEFAULT_TOPIC"
    end
  end

  def connect_mqtt_client
    mqtt_broker = @device.mqtt_broker
    host = params[:mqtt_broker][:host]
    port = params[:mqtt_broker][:port]
    username = params[:mqtt_broker][:username]
    password = params[:mqtt_broker][:password]

    client_id = @device.client_id
    connection_params = {
      host: host,
      port: port,
      client_id: client_id
    }

    connection_params.merge!(
      username: username,
      password: password
    ) if username != '' && password != ''
    MQTT::Client.connect(connection_params)
  end

  def update_mqtt_details
    @device.mqtt_broker.update(host: params[:mqtt_broker][:host],
       port: params[:mqtt_broker][:port],
       username: params[:mqtt_broker][:username],
       password: params[:mqtt_broker][:password])
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
  def devices_dropdown
    devices = Device.all.map{|d| [d.name, d.id ]}
    select_tag 'select device', options_for_select(devices << ['Create New Device', '0'], params[:device_id] || devices.first), class: 'form-control csdropdown', onchange: 'selected_device($(this))'
  end

  def tab_list
    [
      ['globalview', 'Global View'],
      ['mqttclient', 'MQTT Client'],
      ['management', 'Management']
    ]
  end
end

app/views/devices/_device_form.html.erb
<div class="panel-box">
  <div class="panel-head">
    <% if device.persisted? %>
        <h2>Update Device</h2>
    <% else %>
        <h2>Create Device</h2>
    <% end %>
  </div>
  <div class="dc-management-form">
    <%= form_for(device, html: {class: 'form-horizontal', multipart: true}) do |f| %>
        <div class="form-group">
          <div class="col-xs-12 col-sm-6 mb-xs-15">
            <div class="row">
              <div class="col-xs-12 mb-15">
                <%= f.text_field :name, class: 'form-control', placeholder: 'Device Name Here', required: true %>
              </div>
              <div class="col-xs-12">
                <div class="custom-dropdown dm">
                  <%= f.select(:template_id, options_for_select(@templates, :selected => f.object.template_id), {prompt: 'Select Template'}, {class: "form-control", required: true}) %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 mb-xs-15">
            <div class="row">
              <div class="col-xs-12 mb-15">
                <%= f.text_field :interfaces_peripherals, class: 'form-control roundscroll', placeholder: "Interfaces and Peripherals", required: true %>
              </div>
              <div class="col-xs-12">
                <div class="file-upload">
                  <div class="file-select">
                    <div class="file-select-name  device-image">Upload Device Image</div>
                    <%= f.file_field :image %>
                    <div class="imageupload device-image">
                      <div class="file-tab panel-body">
                        <label class="btn btn-default btn-file">
                          <span>Browse</span>
                        </label>
                      </div>
                    </div>
                  </div>
                  <%= image_tag(f.object.image, class: 'display-image', id: 'displayImage') if device.persisted? %>
                </div>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-xs-12 text-center">
              <%= f.hidden_field :user_id, value: current_user.id %>
              <button type="submit" class="btn submit-btn-green device-submit">Submit</button>
            </div>
          </div>
    <% end %>
    </div>
  </div>
</div>

app/views/devices/_device_message.html.erb
<div class="col-xs-12 col-sm-12">
  <div class="panel-box">
    <div class="panel-head">
      <h2>Last Messages</h2>
    </div>
    <div class="row">
      <div class="col-xs-12 col-lg-6 col-md-6 col-sm-12">
        <h4>Sent (Publish)</h4>
        <div class="Tempates-table">
          <div class="device-detail-table">
            <div class="table-responsive">
              <table class="table table-striped fixed_headers three-column">
                <thead>
                <tr>
                  <th>Topic</th>
                  <th>Message</th>
                  <th>Hours</th>
                </tr>
                </thead>
                <tbody style="height:100px;">
                  <% if device.mqtt_broker.connected %>
                    <tr>
                      <td><%= topic %></td>
                      <td><%= message %></td>
                      <td><%= Time.now.strftime('%d-%m-%Y %H:%M:%S') %></td>
                    </tr>
                  <% else %>
                    <tr style="text-align: center;">
                      <td>Device is disconnected</td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-lg-6 col-md-6 col-sm-12">
        <h4>Received (Subscription)</h4>
        <div class="Tempates-table">
          <div class="device-detail-table">
            <div class="table-responsive">
              <table class="table table-striped fixed_headers three-column">
                <thead>
                <tr>
                  <th>Topic</th>
                  <th>Message</th>
                  <th>Hours</th>
                </tr>
                </thead>
                <% if device.mqtt_broker.connected %>
                  <tbody style="height:100px;" id="subscribe-table-body">
                    <%= render partial: '/devices/subscriptions/row' %>
                  </tbody>
                <% else %>
                  <tbody style="height:100px;">
                    <tr style="text-align:  center;">
                      <td>Device is disconnected</td>
                    </tr>
                  </tbody>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/devices/_device_tabs.html.erb
<div role="tabpanel" class="tab-pane active" id="globalview">
  <%= render partial: 'global_view', locals: {device: device} if device %>
</div>
<div role="tabpanel" class="tab-pane" id="mqttclient">
  <%= render partial: 'mqtt_client', locals: {device: device} if device %>
</div>
<div role="tabpanel" class="tab-pane" id="management">
  <%= render partial: 'management_device', locals: {device: device, templates: templates} if device %>
</div>

app/views/devices/_global_view.html.erb
<div class="row">

  <div class="col-xs-12 col-sm-6 p-r-10">
    <div class="panel-box">
      <div class="panel-head">
        <h2><%= device.name.titlecase %></h2>
      </div>
      <div class="panner-in p-one">
        <div class="text-center">
          <%= image_tag(device.image, class: 'device-display-image') %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 p-l-10">
    <div class="panel-box">
      <div class="panel-head">
        <h2>Resume</h2>
      </div>
      <div class="resume-detail roundscroll">
        <ul>
          <li><label>Title :</label><%= device.api_json&.dig('info', 'title') %></li>
          <li><label>Version :</label><%= device.api_json&.dig('info', 'version') %></li>
          <li><label>Connection Status :</label><%= device.mqtt_broker.connected? ? 'Connected' : 'Not connected' %></li>
          <li><label>Description :</label><%= device.api_json&.dig('info', 'description') %></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-6 p-r-10">
    <div class="panel-box p-three">
      <div class="panel-head">
        <h2>API Commands</h2>
      </div>
      <div class="command-detail roundscroll">
      	See Management tab
<!--        
        <ul>
          <li>
            <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt</h3>
            <p>It is a long established fact that a reader </p>
          </li>
          <li>
            <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt</h3>
            <p>It is a long established fact that a reader </p>
          </li>
          <li>
            <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt</h3>
            <p>It is a long established fact that a reader </p>
          </li>
          <li>
            <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt</h3>
            <p>It is a long established fact that a reader </p>
          </li>
          <li>
            <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt</h3>
            <p>It is a long established fact that a reader </p>
          </li>
        </ul>
    -->
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 p-l-10">
    <div class="panel-box p-three mb-15">
      <div class="panel-head ">
        <h2>Interfaces</h2>
      </div>
      <div class="interface-detail roundscroll">
        <ul>
          <% unless device.interfaces.blank? %>
              <% device.interfaces.each do |interface| %>
                  <li><%= interface %></li>
              <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/devices/_management_device.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="panel-box">
      <div class="panel-head">
        <h2>Import API JSON</h2>
      </div>
      <div class="dc-management-form">
        <%= form_for device, html: {class: 'form-horizontal', multipart: true} do |f| %>
          <div class="form-group">
            <div class="col-xs-12 col-sm-12 mb-xs-15">
              <div class="row">
                <div class="col-xs-12 col-md-3 mb-xs-15">
                  <div class="custom-dropdown">
                    <%= f.select :template_id, options_for_select(templates), {class: "form-control", prompt: 'Select Template', required: true} %>
                  </div>
                </div>
                <div class="col-xs-12 col-md-9 mb-xs-15">
                  <div class="export-section">
                    <div class="left-section">
                      <div class="file-upload">
                        <div class="file-select">
                          <div class="file-select-name" id="noFile">JSON Name Here</div>
                          <%= f.file_field :api_json, id: "chooseFile" %>
                          <div class="file-select-button" id="fileName">Browse</div>
                        </div>
                      </div>
                    </div>
                    <div class="right-section">
                      <%= f.button :submit, class: 'btn import-btn' do %>
                        Import
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="col-md-12 col-sm-12">
  <div class="panel-box bottom">
    <div class="panel-head">
      <div class="row">
        <div class="col-md-6 col-xs-12">
          <h2>Current API</h2>
          <div class="status-area roundscroll ">
            <% if device.api_json.present? %>
              <%= render partial: 'devices/show_api_data', collection: device.api_json, as:  :api_json %>
            <% end %>
          </div>
        </div>
        <!--
        <div class="col-md-6 col-xs-12">
          <div class="buttons">
            <div class="connnect-button dbtn">
              <a href="#" class="desable-button update">
                <span class="c-btn-icn">
                    <img src="../assets/updaticon.png" alt=".">
                </span>
                <span class="c-btn-txt">UPDATE</span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-xs-12">
          <div class="content roundscroll">
            <h3>Sinapse Energia</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
            <h5>Terms of service</h5>
            <div class="text-green">
              <p>https://api.sinapeenrgia.com</p>
            </div>
            <h5>Connection details</h5>
            <div class="table-responsive bottom-table">
              <table class="table table-striped">
                <thead>
                <tr>
                  <th>URL
                  </th>
                  <th>Scheme
                  </th>
                  <th>Description
                  </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                  <td>Lorem ipsum dolor sit amet,</td>
                  <td>Lorem</td>
                  <td>
                    <span class="custom-dropdown ">
                      <select class="form-control">
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>SLorem ipsum dolor sit amet,</option>
                      </select>
                    </span>
                  </td>
                </tr>
                <tr>
                  <td>Lorem ipsum dolor sit amet,</td>
                  <td>Lorem</td>
                  <td>
                    <span class="custom-dropdown ">
                      <select class="form-control">
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>SLorem ipsum dolor sit amet,</option>
                      </select>
                    </span>
                  </td>
                </tr>
                <tr>
                  <td>Lorem ipsum dolor sit amet,</td>
                  <td>Lorem</td>
                  <td>
                    <span class="custom-dropdown ">
                      <select class="form-control">
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>SLorem ipsum dolor sit amet,</option>
                      </select>
                    </span>
                  </td>
                </tr>
                <tr>
                  <td>Lorem ipsum dolor sit amet,</td>
                  <td>Lorem</td>
                  <td>
                    <span class="custom-dropdown ">
                      <select class="form-control">
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>SLorem ipsum dolor sit amet,</option>
                      </select>
                    </span>
                  </td>
                </tr>
                <tr>
                  <td>Lorem ipsum dolor sit amet,</td>
                  <td>Lorem</td>
                  <td>
                    <span class="custom-dropdown ">
                      <select class="form-control">
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>SLorem ipsum dolor sit amet,</option>
                      </select>
                    </span>
                  </td>
                </tr>
                <tr>
                  <td>Lorem ipsum dolor sit amet,</td>
                  <td>Lorem</td>
                  <td>
                    <span class="custom-dropdown ">
                      <select class="form-control">
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>SLorem ipsum dolor sit amet,</option>
                      </select>
                    </span>
                  </td>
                </tr>
                <tr>
                  <td>Lorem ipsum dolor sit amet,</td>
                  <td>Lorem</td>
                  <td>
                    <span class="custom-dropdown ">
                      <select class="form-control">
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>SLorem ipsum dolor sit amet,</option>
                      </select>
                    </span>
                  </td>
                </tr>
                <tr>
                  <td>Lorem ipsum dolor sit amet,</td>
                  <td>Lorem</td>
                  <td>
                    <span class="custom-dropdown ">
                      <select class="form-control">
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>Lorem ipsum dolor sit amet,</option>
                        <option>SLorem ipsum dolor sit amet,</option>
                      </select>
                    </span>
                  </td>
                </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div> -->
      </div>
    </div>
  </div>
</div>

app/views/devices/_mqtt_client.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12">
    <div class="panel-box">
      <div class="panel-head">
        <h2>MQTT Broker</h2>
      </div>
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="MQTT-Client-form">
            <%= form_for device.mqtt_broker, url: "/devices/#{device.id}/connect", method: 'POST', html: {class: 'mqtt-form', id: 'mqtt_frm'} do |f| %>
              <%= hidden_field_tag "mqtt_broker[client_id]", device.client_id %>
              <%= hidden_field_tag "mqtt_broker[topic]", device.topic %>
              <div class="form-group">
                <div class="row">
                  <div class="col-lg-6 col-md-12 col-sm-12 mb-xs-15">
                    <%= f.text_field :host, class: 'form-control mqtt-pd', placeholder: "URL" %>
                  </div>
                  <div class="col-lg-6 col-md-12 col-sm-12 mb-xs-15">
                    <%= f.text_field :port, class: 'form-control mqtt-pd', placeholder: "PORT" %>
                  </div>
                  <div class="col-lg-6 col-md-12 col-sm-12 mb-xs-15">
                    <%= f.text_field :username, class: 'form-control mqtt-pd', placeholder: "User" %>
                  </div>
                  <div class="col-lg-6 col-md-12 col-sm-12 mb-xs-15">
                    <%= f.password_field :password, class: 'form-control mqtt-pd', placeholder: "Password" %>
                  </div>
                </div>
              </div>
              <input type="hidden" id='conn_type'/>
            <% end %>
          </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="row">
            <div class="col-md-6">
              <div class="buttons">
                <div class="disconnnect-button dbtn">
                  <div class="desable-button">
                    <%= link_to '', onclick: "connectMqtt_device($(this))", 'data-id' => device.id, remote: true do %>
                      <span class="c-btn-icn">
                        <img src="../assets/wifi-disconnect.png" alt="...">
                      </span>
                      <span class="c-btn-txt">disconnect</span>
                    <% end %>
                  </div>
                </div>
                <div class="connnect-button dbtn">
                  <div class="desable-button">
                    <%= link_to '', onclick: "connectMqtt_device($(this))", class: 'device-connect', 'data-id' => device.id, remote: true do %>
                      <span class="c-btn-icn"><img src="../assets/wifi-connect.png" alt=".">
                      </span>
                      <span class="c-btn-txt">connect</span>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <h4>Status</h4>
              <div class="status">
                <div class="status-area status-center">
                  <h2>
                    <% if device.mqtt_broker.connected %>
                      Connected
                    <% else %>
                      Disconnected
                    <% end %>
                  </h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'devices/device_message', locals: {device: @device, message: @message, topic: @topic} %>

app/views/devices/_show_api_data.html.erb
<div class="text-in ">
  <% is_hash = api_json[1].is_a?(Hash) %>
  <div class="lineone">
    <div class="text-orange">
      <p><%= api_json[0] %>:</p>
    </div>
    <div class="<%=  is_hash ? 'pad-left-10' : 'text-green' %>">
      <% if is_hash %>
          <%= render partial: 'devices/show_api_data', collection: api_json[1], as:  :api_json %>
      <% else %>
          <p>"<%= api_json[1] %>"</p>
      <% end %>
    </div>
  </div>
</div>

app/views/devices/edit.html.erb
<%= render template: 'devices/new' %>

app/views/devices/index.html.erb
<div class="alert-success device-alert-message"></div>
<div class="top-panel" id="device-index">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="page-title">Devices</div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="page-breadcrumbs">
          <ul>
            <li>
              <a href="#">Devices</a>
            </li>
            <li>IOT Hub Scinap</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="middle-container">
  <div class="tab-section page-tab">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12 col-sm-12">
          <!-- Nav tabs -->
          <ul class="nav nav-tabs" role="tablist">
            <% tab_list.each_with_index do|(ref, text), index| %>
              <li role="presentation" class="<%= index.eql?(0) ? 'active' : '' %> js-device-li">
                <%= link_to text, '#' + ref, 'aria-controls' => ref, role: 'tab', 'data-toggle' => 'tab', class: 'js-device-tab' %>
              </li>
            <% end %>
          </ul>
          <div class="col-xs-12">
            <div class="tabing-select">
              <div class="custom-dropdown select whtab">
                <%= devices_dropdown %>
              </div>
            </div>
          </div>
          <!-- Tab panes -->
          <div class="tab-content" id="deviceTabs">
            <%= render partial: 'device_tabs', locals: {device: @device, templates: @templates, message: @message, topic: @topic} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="clear"></div>

<script type="text/jscript">
function connect_mqtt() {
$('#conn_type').val('connect');
$('#mqtt_frm').submit();
}
</script>

app/views/devices/new.html.erb
<div class="top-panel">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="page-title">Device Management</div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="page-breadcrumbs">
          <ul>
            <li><a href="#">Devices</a></li>
            <li>IOT Hub Scinap</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="middle-container">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-12">
        <%= render partial: 'devices/device_form', locals: {device: @device} %>

        <div class="col-xs-12 col-sm-12">
          <div class="panel-box">
            <div class="panel-head">
              <h2>Devices</h2>
            </div>
            <div class="device-detail-table">
              <div class="table-responsive">
                <table class="table table-striped fixed_headers three-column">
                  <thead>
                    <tr>
                      <th>Device Name</th>
                      <th>Tempate Name</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody style="height:175px;">
                    <% @devices.each do |device| %>
                      <tr>
                        <td><%= device.name %></td>
                        <td><%= device.template.name %></td>
                        <td><%= link_to image_tag('edit-icon.svg'), edit_device_path(id: device.id) %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="clear"></div>

<script>
  $('#device_image').change(function(event) {
      $('#displayImage').attr('src',URL.createObjectURL(event.target.files[0]));
  })
</script>