config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root to: 'devices#index'
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }

  get 'terms', to: 'static_pages#terms'
  get 'help', to: 'static_pages#help'

  resources :templates do
    member do
      get :get_template
    end
  end
  resources :devices do
    member do
      get :get_device
      get :get_messages
      post :connect
      post :disconnect
    end
  end
end

app/views/templates/_index.html.erb
<div class="container-fluid">
  <div class="row">
  <% if !template.nil? %>   
  <div class="col-xs-12 col-sm-6 p-r-10">
      <div class="panel-box my-panel fix-box">
        <div class="panel-head">
          <h2><%= template.name %></h2>
        </div>
        <div class="panner-in p-one">
          <div class="text-center">
            <%= image_tag(template.image, class: 'device-display-image')%>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 p-l-10">
      <div class="panel-box my-panel fix-box">
        <div class="panel-head">
          <h2>Overview</h2>
        </div>
        <div class="overview-container roundscroll">
          <div class="panner-in p-two ">
            <h3><%= template.hardware_json.dig('CommBoard', 'Name') %></h3>
            <p><%= template.hardware_json.dig('CommBoard', 'Description') %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="panel-box p-three ">
        <div class="panel-head">
          <h2>Description</h2>
        </div>
        <% if template.hardware_json.present? %>
          <div class="discription-container roundscroll">
            <%= render partial: 'templates/show_hardware_data', collection: template.hardware_json, as: :hardware_json %>
          </div>
        <% end %>
      </div>
    </div>
    <% end %>
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="buttonpnnl">
        <button class="button-create device" onclick="window.location='devices/new';">create device</button>
      </div>
    </div>
  </div>
</div>

app/views/templates/_show_hardware_data.html.erb
<div class="text-in ">
  <div class="panner-in ">
    <% is_hash = hardware_json[1].is_a?(Hash) %>
    <div class="lineone">
      <div class="key-text">
        <p><%= hardware_json[0] %> : </p>
      </div>
      <div class="<%= is_hash ? 'pad-left-10' : 'key-text' %>">
        <% if is_hash %>
          <%= render partial: 'templates/show_hardware_data', collection: hardware_json[1], as: :hardware_json %>
        <% else %>
          <p>&nbsp;<%= hardware_json[1] %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/templates/_template_form.html.erb
<div class="col-xs-12 col-sm-12">
  <div class="panel-box">
    <div class="panel-head">
      <% if template.persisted? %>
          <h2>Update Tempate</h2>
      <% else %>
          <h2>Create Tempate</h2>
      <% end %>
    </div>
    <div class="dc-management-form">
      <%= form_for(template, html: {class: 'form-horizontal', multipart: true}) do |f| %>
        <div class="form-group">
          <div class="col-xs-12 col-sm-12 mb-xs-15">
            <div class="row">
              <div class="col-xs-12 col-sm-5 mb-xs-15">
                <%= f.text_field :name, class: 'form-control', placeholder: "Tempate Name Here" %>
              </div>
              <div class="col-xs-12 col-sm-7">
                <div class="file-upload cs-templete">
                  <div class="file-select">
                    <div class="file-select-name" id="noFile">JSON Name Here</div>
                    <%= f.hidden_field :json_name, id: 'json_name' %>
                    <%= f.file_field :hardware_json, id: "chooseFile" %>
                    <div class="file-select-button" id="fileName">Import JSON</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 mb-xs-15">
            <div class="row">
              <div class="col-xs-12 col-sm-5 mb-xs-15 template-image">
                <div class="file-upload">
                  <div class="file-select">
                    <div class="file-select-name  device-image">Upload Template Image</div>
                    <%= f.file_field :image %>
                    <div class="imageupload device-image">
                      <div class="file-tab panel-body">
                        <label class="btn btn-default btn-file">
                          <span>Browse</span>
                        </label>
                      </div>
                    </div>
                  </div>
                  <%= image_tag(f.object.image, class: 'display-image', id: 'templateImage') if template.persisted? %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-12 text-center">
            <%= f.submit 'Submit', class: 'btn submit-btn-green' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script>
  $('#template_image').change(function(event) {
    $('#templateImage').attr('src',URL.createObjectURL(event.target.files[0]));
  });
</script>

app/views/templates/edit.html.erb
<%= render template: 'templates/new' %>

app/views/templates/index.html.erb
<div class="top-panel">
   <div class="container-fluid">
      <div class="row">
          <div class="col-xs-12 col-sm-6">
              <div class="page-title">Templates</div>
          </div>
          <div class="col-xs-12 col-sm-6">
              <div class="page-breadcrumbs">
                 <ul>
                    <li><a href="#">Templates</a></li>
                 </ul>
              </div>
          </div>
      </div>
   </div>
</div>
<div class="middle-container">
  <div class="tab-section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <div class="custom-dropdown select whtab">
            <%= templates_dropdown  %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="template-index">
    <%= render partial: 'templates/index', locals: {template: @template} %>
  </div>
</div>
<div class="clear"></div>

app/views/templates/new.html.erb
<div class="top-panel">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="page-title">Template Management</div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="page-breadcrumbs">
          <ul>
            <li><a href="#">Devices</a></li>
            <li>IOT Hub Scinap</li>
          </ul>
       </div>
      </div>
    </div>
  </div>
</div>
<div class="middle-container">
  <div class="container-fluid">
    <div class="row">
      <%= render partial: 'templates/template_form', locals: {template: @template} %>
      <div class="col-xs-12 col-sm-12">
        <div class="panel-box">
          <div class="panel-head">
            <h2>Tempates</h2>
          </div>
          <div class="device-detail-table roundscroll">
            <div class="table-responsive">
              <table class="table table-striped fixed_headers two-column">
                <thead>
                  <tr>
                    <th>Tempate Name</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody style="height:175px;">
                  <% @templates.each do |t| %>
                    <tr>
                      <td><%= t.name %></td>
                      <td><%= link_to image_tag('edit-icon.svg'), edit_template_path(id: t.id) %></td>
                      <!--<td><a href><img src="../assets/edit-icon.svg" alt="edit"></a></td>-->
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="clear"></div>